# why numpy: in python array package does not allow multidimentional array that why we have to used the numpy

In [4]:
from numpy import *   # numpy is used in array because array does not support multidimensional array
arr=array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
# to perform scientific operation we used the numpy

In [8]:
# as we know the array take a same data type
from numpy import *
arr=array([1,2,3,3.5])  # so here i had mention a float data type on it,, so in numpy it will convert all the value to float ,because float take 4 byte
print(arr.dtype)

float64


In [9]:
print(arr)  # as i said before ,now the all value it change to float

[1.  2.  3.  3.5]


# but if we want a specific data type than we can mention it 

In [12]:
arr=array([1,2,3,3.5],int)  # so it will take only integer value
print(arr)


[1 2 3 3]


In [ ]:
# the way by which we can create a array in numpy

# linspace

In [21]:
# linspace take 3 argument 1.start,2.end 3. is dividing part .mean from start to end in how many parts it  want to divide 
arr=linspace(1,10,2)

In [22]:

print(arr)

[ 1. 10.]


In [23]:
arr=linspace(1,10,5) # here i want to divide in 5 parts
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


# if we dont specify the parts ,so by default it will convert into 50 parts

In [25]:
arr=linspace(1,10)
print(arr)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


# arange  # it wil add the third argument differnce from starting to end point


In [30]:
arr=arange(1,10,2)  #  2 willadd the number difference

In [31]:
print(arr)

[1 3 5 7 9]


In [2]:
# to get LL the even number
from numpy import *
a=arange(0,10,2)  # 1 argument=starting point,2nd argument=endpoint and 3 argument will the difference
print(a)

[0 2 4 6 8]


# logspace

In [33]:
arr=logspace(1,10,2)  # in log we get the log value
print(arr)

[1.e+01 1.e+10]


# zeros and ones

In [39]:
from numpy import *
ar=zeros(4)   #   number of zero we want in the array
print(ar)

[0. 0. 0. 0.]


In [40]:
ar=ones(4)   #   number of ones we want in the array
print(ar)

[1. 1. 1. 1.]


# but the above code in float point if we want  in integer format than

In [42]:
ar=zeros(4,int)   #   number of zero we want in the array
print(ar)

[0 0 0 0]


In [43]:
# sme for one
ar=ones(4,int)   #   number of ones we want in the array
print(ar)

[1 1 1 1]


# if you want to acces the 4 number of 1 dimention than how to write it

In [1]:
import numpy as n
a=n.array([
    [1,2,3,4,5],   # this is the o dimention
    [6,7,8,9,10]   # 1 dimention
])

In [7]:
print(a[1,4])    # esmai kaise leyga. ki a ka 1 index ka 4 value chhahiyeh

10


# 3 dimension   this is how to declare a 3 dimension array in numpy

In [11]:
from numpy import *
aa=array([
    [[1,2,3],[4,5,6]],    #0 dimension, # 0 dimension mai v 2 array hai.jismai ek 0 and dusra 1 dimension hai
    
       [[1,2,3],[4,5,6]]# 1 dimension # 1 dimension mai v 2 array hai.jismai ek 0 and dusra 1 dimension hai
    
])# 

In [12]:
aa.ndim

3

In [13]:
aa[0,1,2]   #yeh 0 dimention ke andar ke 1 dimension ka 2 index value leyga

6

# slicing in numpy,some interestin g concept

In [16]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],   # 0 dimension
                [6, 7, 8, 9, 10]]) # 1 dimension

# starting 0 include kareyga, end ending 2 hai mean as we know 2 ko exclude kareyga.eska matlan 0 and 1 dimension leyga 
  # donu dimension mai sey 2 index ke value print kareyga
print(arr[0:2, 2])    # starting 0 include kareyga, end ending 2 hai mean as we know 2 ko exclude kareyga.eska matlan 0 and 1 dimension leyga 

[3 8]


In [17]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],      # 0 DIMENSION
                [6, 7, 8, 9, 10]])   # 1 DIMENSION

print(arr[0:2, 1:4]) # 0 sey 1 tkh leyga, donu array mai 1 index sey 3 index takh ki value print kareygA

[[2 3 4]
 [7 8 9]]


# this concept i will learn from w3 school

In [5]:
import numpy
n, m = map(int, input().split()) 
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2
1 4
21 34
[[ 1 21]
 [ 4 34]]
[ 1  4 21 34]


### 

In [20]:
from numpy import *
array1=array([
    [1,2,3],  # 0 dimension
    [4,5,6]    # 1 dimension
])
# esmai sey tujhko 0 dimesnion ki 2 index value print karna hai
print(array1[0,2] )    # esmai 0 dimension ka 2 index ki value print kia

3

#  agar o and 1 dimension ke 1 to 3 index value print karna hai

In [22]:
# pehle , comma mai array ka dimension mention karte hai n comma ke baad mai index value

array1[0:2,1:4]    # aise denge yeh condition


array([[2, 3],
       [5, 6]])

In [1]:
from numpy  import *
a=array([
       [2,13,4,5],
    [12,3,41,12],
    
    ])

In [3]:
d=a[0:2,1:3]
print(d)
pd[::-1]  # esmai niche ka rows uppar chaley jayega

[[13  4]
 [ 3 41]]


array([[ 3, 41],
       [13,  4]])

In [10]:
from numpy import *
a,b=map(int,input())

12 23


ValueError: invalid literal for int() with base 10: ' '

# 

In [ ]:
a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))
