# multidimentional array

In [21]:
from numpy import *
a=array([
    [1,2,3],    # 1 dimentiona 
        [3,4,5]   # 2 dimentional
])


In [24]:
print(a)
print("number of dimension of array is:",a.ndim)   # to get to know the type of dimenstion of a array.call afunction ndim

[[1 2 3]
 [3 4 5]]
number of dimension of array is: 2


# SOME FUNCTION IN THIS ARE GIVEN BELOW

In [15]:
# TO GET TO KNOW WHICH DATA TYPE WE ARE WORKING WITH
print(a.dtype)   # by using this function we will get to know the data type of a array.dtype itself it say as a data type

int32


In [16]:
print(a.ndim)  # dimention of a array

2


# if we want to know the number of rows and column in a array than use this function

In [20]:
print(a.shape)  #it will tell number of rows and column

(2, 3)


# using size it wil give total size of array

In [23]:
a.size    # so total size of array is

6

# important concept

# how to convert multidimentional array to singal dimentional array

In [35]:
# by using the function name called flatten()
from numpy import *
z=array([
    [1,2,3,4],
    [5,6,7,8],
    
])

In [41]:
z.shape  # no of rows and column


(2, 4)

In [43]:
z.flatten()  s   # by using this function the array of multidimentional will get to singal

array([1, 2, 3, 4, 5, 6, 7, 8])

#  how to convert multidimentional array to single dimentional array

In [25]:
from numpy import *
singal=array([
    [1,2,3,4,5,11],
    [6,7,8,9,10,12]
])
singal.size  # esse number of element pta chal jayega ,us hisbah sey reshape method sey row and column decide kar leyna

12

In [59]:
singal1=singal.flatten()   #multidimentional ko singal mai convert kia
print(singal1)

[ 1  2  3  4  5 11  6  7  8  9 10 12]


# now the singal dimentional array is stored in singal 1 ,so now i wil call a function reshape to convert that singal dimentional array to multidimentional array

In [63]:
multi=singal1.reshape(3,4)    # in re shape we have to mention the number of rows and column
print(multi)

[[ 1  2  3  4]
 [ 5 11  6  7]
 [ 8  9 10 12]]


In [64]:
# if we want than we can performone more way

In [73]:
multi1=multi.reshape(2,3,2)#  here it is telling as the 2 dimentional array with 3 rows and 2 column


In [74]:
print(multi1)

[[[ 1  2]
  [ 3  4]
  [ 5 11]]

 [[ 6  7]
  [ 8  9]
  [10 12]]]


# how to convert dimentional array to matrix  

In [75]:
from numpy import *
z=array([
    [1,2,3],
    [4,5,6]
])

In [82]:
print(z)  #
type(z)


[[1 2 3]
 [4 5 6]]


numpy.ndarray

# to convert into matrix use the function call.matrix

In [83]:
# to convert into matrix use the function call.matrix
mat=matrix(z)

In [85]:
print(mat)
type(mat) # checking the type of it

[[1 2 3]
 [4 5 6]]


numpy.matrix

# now after converting it into matrix we can perform many matrix(mathmatical operation)

# we can take matrix value from the user

In [92]:
from numpy import *
gk=matrix('1 ,2 ,3 ,4;5 ,6 ,7 ,8 ')  # this is the way by which we can take input from the user.. to make a separate we use ; semicolon

In [93]:
print(gk)

[[1 2 3 4]
 [5 6 7 8]]


In [94]:
#converting this matrix into  3 rows and 3 colum
gk=matrix('1,2,3;4,5,6;7,8,9')

In [95]:
print(gk)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [104]:
#to get all the diagonal element of matrix


In [106]:
print(gk.diagonal())

[[1 5 9]]


In [109]:
print(diagonal(gk))

[1 5 9]


In [120]:
from numpy import *
a=array([
    [1,2,3],   # it will consider whole '[]' as a 0
    [4,5,6]    # it will consider whole '[]' as a 1
])

In [121]:
print(a)

[[1 2 3]
 [4 5 6]]


In [122]:
for i in range(len(a)):
    print(i)

0
1


# multiplication of matrix take place only agar pehle(1) table ka column=2 table ka rows ho tabhi possible hai

In [1]:

X = [[1,2,3], # 0 rows 
    [4,5,6],  # 1 rows
    [7,8,9]]    # here 3*3   ------>>>>>>>eska columna niche wale ke row ke barabr hai


# huko pta hai multiplication kaisa hota hia,multiplication tabhi possible hai 1 ka column 2 ke rows ke barabar ho

#------------>>multiplication kaise jata hai humko pta hai,1 rows of 1 ka 1 column ko multiply kareyga
#---- eska pattern aisa hoga    --------o 
#                                           
#
# 
Y = [[10,11,12],  
      [13,14,15],  
      [16,17,18]]    # yeh v 3*3 ka matrix hai ----->>>>>> eska 3 rows hai   -----so condition satisfied huwa
 
result = [[0,0,0],  
               [0,0,0],  
              [0,0,0]] 

for i in range(len(X)): 
    
    #print(i)# len of x define the number of rows
    
    for j in range(len(Y[0])):    #  this is used when we dont have sme number of rows and column in both table
    
        for k in range(len(Y)):  #row column*rows column  #as we know ki pehle wale ka column increment hoga, and second wale ka rows
            
            result[i][j] += X[i][k] * Y[k][j]  
            
            # firts []  decide the rows n [] second column
# =====>>>  esmai result ke set mai pehle set mai 0 row ke 0 column mai values assign hoga--->> i=0 and j=0== x[i=0 rows ka][k=0 column]*y[k=0 columnka ,j=rows]  ##   first iteration mai jabh takh k ki value puri nhi hpgi tabh takh,k ki value hoen ke baaad j ka satisfied hoga 
#-->>>  abhi i=0 hi hai but k=1 ho gya toh x[i=0 row ka ][k=1 pehle column value]  and y ka[k=1 rows,y=0 column]       
            
for r in result:  
     print(r)

[84, 90, 96]
[201, 216, 231]
[318, 342, 366]


In [3]:
# it is used when we dont have a same number of rows andcolumn in both table
from numpy import *
a=array([
	[2,3,4],     # jaise idhar A table mai 2 rows and 3 column hai,
	[1,2,3]])
b=array([
	[1,2],    # and eska 3 rows and 2 column hai
	[3,4],
	[4,5]])
re=array([
	[0,0],
	[0,0]])
for i in range(len(a)):
	for j in range(len(b[0])):  # so donu table ka rows and column alah hai eslia y[0] dalna 
		for k in range(len(b)):
			re[i][j]+=a[i][k]*b[k][j]
for l in re:
	print(l)

[27 36]
[19 25]


In [4]:
import numpy
a=numpy.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
a.ndim  # 3 dimenstion 

3

In [18]:
d=a.flatten()
print(d)
d.reshape(2,6)   # 2 rows and 6 column

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [12]:
from numpy import *
a=array([
    [1,2,3,4],
    [2,3,4,5]
])
d=a.flatten()
print(d)
d.reshape(2,4)  # we made it into 2 rows and 4 column

[1 2 3 4 2 3 4 5]


array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

# simple way to do a matrix multiplication

In [13]:
X = [[1,2],  
    [4,5]]        
y=[[1,3],
   [2,5]]
z=[[0,0],
  [0,0]] 
for i in range(len(X)):
    for j in range(len(y)):
        for k in range(len(y)):   # multiplication mai 1 X ka column increment hoga, q ki hum multiplilaction mai ulta l mai kareteh hai,
            # (so pehle ka Column increment hoga es lia k as as columna) and [dusre ka rows increment leyga  ,to k as a rows hoga]
            z[i][j]= z[i][j]+X[i][k] * Y[k][j]
for r in z:  
     print(r)

[36, 39]
[105, 114]


In [12]:
from numpy import *
bd=array([
    [12,3,4],
    [6,7,8]
])


In [9]:
print(bd.ndim)   # bd is a array inside which the ndim method for finding the dimension

2


In [10]:
#mn hnumpy.method(jo shape finr kareyga ki number of rows and column hoga)
print(bd.shape)

(2, 3)


In [17]:
import numpy
bd=numpy.asarray([
    [1,2,3],
    [5,6,7]
]) 
m=numpy.matrix(bd)# inside the numpy matrix there is a method call the matrix,so this is how we will call the method inside the class

In [18]:
print(m)

[[1 2 3]
 [5 6 7]]


In [19]:
type(m)

numpy.matrix

In [20]:
type(bd)

numpy.ndarray

In [1]:
from numpy import *
a=array([
    [1,2,3],
    [3,4,5]
])

In [2]:
print(a)
a.ndim

[[1 2 3]
 [3 4 5]]


2

In [3]:
f=a.flatten()

In [4]:
print(f)

[1 2 3 3 4 5]


In [5]:
f.reshape(2,3)

array([[1, 2, 3],
       [3, 4, 5]])