In [2]:
import numpy as np
a=np.zeros((2,3))    # 2 rows and 3 column withh zeros
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


## to fill the numpy array with the paticular number

In [4]:
a=np.full((2,3),10)   # full method is used to assign the value in numpy,first it take how many rows and column is requied and than the value
print(a)

[[10 10 10]
 [10 10 10]]


## numpy take arange method for ranging perpose

In [12]:
import numpy as n

b=n.arange(1,10)   # it will start from 1 and end at 9 
print(b)

[1 2 3 4 5 6 7 8 9]


## and agar values chahiyeh with gaps so 3 argument we will take to do that  form

In [15]:
import numpy as n

b=n.arange(1,10,2)   # it will start from 1 and end at 9 with the difference of 2
print(b)

[1 3 5 7 9]


##  agar koe v random values chahiyeh toh ramdom method ko call karnge

In [21]:
import numpy as n
k=n.random.randint(100,200,10)   # mean 100 sey 200 ke bich koe v 10 random value chaiyeh
print(k)

[144 169 162 150 118 163 197 141 184 134]


## vertically ,horizentally and the column stack

In [39]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
# agar do array ko vertically stack karna hai so use
np.vstack((a,b))  # this is how vertically yeh joint hog

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [37]:
# agar single variable of numpy hai so we will used the flatten method,but 2 ya use jada ko ekk sath single dimension mai use ke lia 
# hstack()
from numpy import *
a=array([[1,2,3,4],[4,5,6,7]])
a.flatten()

array([1, 2, 3, 4, 4, 5, 6, 7])

In [40]:
# agar horizentally join karna hai toh,between two variable
np.hstack((a,b))  # this is how vertically yeh joint hog

array([1, 2, 3, 4, 4, 5, 6, 7])

In [41]:
# agar 1 pehle variable ki value 1 pehel column mai chahiyeh and same for 2 ki so,we will used column
np.column_stack((a,b))   # so esne kya kia rows ko column mai convert kar dia, same as 1 

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

## jaise 2 numpy array dia hai and unke bich humko common jo value hai wah jaana hai ,so we will use intersect1d it is inside the numpy package

In [42]:
# jaise 2 numpy array dia hai and unke bich humko common jo value hai wah jaana hai ,so we will used 
# intersection
import numpy as np
a=np.array([1,2,3,4,5,6,7])
b=np.array([5,6,7,8])
# agar indonu ke bich humko (same same konse) common value janna hai so we will used intersect 
np.intersect1d(a,b)    # so jov a and b mai coommon hoga wah deyga

array([5, 6, 7])

## jaise 2 numpy array dia hai and unke bich humko alag alag  jo value hai wah jaana hai ,so we will use setdiff1d it is inside the numpy package


In [5]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
b=np.array([5,6,7,8])
# agar indonu ke bich humko common value janna hai so we will used intersect 
np.setdiff1d(a,b)   # esmai a pehle hai toh uska unique value deyga,(a) and (b) ka check karyega jo v unique hoga (a) mai wah print kareyga

array([1, 2, 3, 4])

In [48]:
np.setdiff1d(b,a)   # esmai b pehle hai toh uska unique value deyga,b and a ka check karyega jo v unique hoga b mai wah print kareyga

array([8])

##  if sum of numpy array chahiyeh toh

In [11]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.sum([a,b])  # yeh donu numpy ko add karke deydeyga
print(result)

21


# agar koe paticluar axis mai karna hai toh and axis 0 mai column wise add kareyga

In [15]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.sum([a,b],axis=0)  # yeh donu numpy ko add karke deydeyga,axis 0 mai column wise,jaise 1+4=5,2+5=7,3+6=9
print(result)   # so we got the output

[5 7 9]


  ## axis 1 mai rows wise add karta hai

In [17]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.sum([a,b],axis=1)  # yeh donu numpy ko add karke deydeyga,axis 1 mai rows wise,jaise 1+2+3=6 and 4+5+6=15
print(result)

[ 6 15]



##  mean ,medium and standard deviation

##  mean

In [40]:
import numpy as np
a=np.array([1,2,3,30])
#np.mean(a)        # this is how we can called the method and another way is
a.mean()   # a is a type of numpy so directly we can called it

9.0

## medium

In [42]:
import numpy as np
a=np.array([1,2,3,30])
np.median(a)

2.5

## standard deviation

In [43]:
import numpy as np
a=np.array([1,2,3])
np.std(a)

0.816496580927726

In [ ]:
from numpy import *
a=array([10,20,30])
b=arrayay([1,2,3])
s=